name: Update system calls data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 2' # Each tuesday
  # also run on repo changes
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  update-tables:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: install packages data
        run: sudo apt-get update

      # without x32 headers we get i386 data for x32
      - name: install x32 headers
        run: sudo apt-get install libc6-dev-x32

      - name: Checkout syscalls-table
        uses: actions/checkout@v4
        with:
          path: syscalls-table/
          ref: master

      - name: Checkout Linux
        uses: actions/checkout@v4
        with:
          path: linux
          repository: torvalds/linux

      - name: Update system calls data
        working-directory: syscalls-table/
        run: |
          bash scripts/update-tables.sh $GITHUB_WORKSPACE/linux/

      - name: Check linux version
        working-directory: linux/
        run: |
          LINUX_VER=$(make kernelversion)
          echo "VERSION=$LINUX_VER" >> $GITHUB_ENV

      # taken from https://stackoverflow.com/a/75809743
      - name: Exit if only kernel version change
        working-directory: syscalls-table/
        run: |
          if [ `git diff system_calls | wc -l` == 7 ]; then
            gh run cancel ${{ github.run_id }}
            gh run watch  ${{ github.run_id }}
          fi

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          path: syscalls-table/
          signoff: true
          base: master
          branch: update/tables
          title: 'update: update syscalls tables.'
          body: |
            This autogenerated PR updates the tables of syscalls from kernel ${{ env.VERSION }}. Do not edit this PR.
            ```
          commit-message: 'update syscalls tables for kernel ${{ env.VERSION }}.'
          token: ${{ secrets.GITHUB_TOKEN }}
