name: Update Syscalls Tables

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1' # Each monday

jobs:
  update-tables:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout syscalls-table ⤵️
        uses: actions/checkout@v4
        with:
          ref: master
      
      - name: Checkout linux ⤵️
        run: |
          git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git linux/ --depth=1
          
      - name: Fetch linux version
        working-directory: linux/
        run: |
          MAJ_VERSION=$(grep VERSION Makefile | head -n 1 | awk '{print $3}')
          PATCH_VERSION=$(grep PATCHLEVEL Makefile | head -n 1 | awk '{print $3}')
          SUBLEVEL_VERSION=$(grep SUBLEVEL Makefile | head -n 1 | awk '{print $3}')
          EXTRA_VERSION=$(grep EXTRAVERSION Makefile | head -n 1 | awk '{print $3}')
          echo "VERSION=$MAJ_VERSION.$PATCH_VERSION.$SUBLEVEL_VERSION$EXTRA_VERSION" >> $GITHUB_ENV
          
      - name: Bump syscalls-tables
        run: |
          make KERNELSRC=$GITHUB_WORKSPACE/linux/
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          signoff: true
          base: master
          branch: update/tables
          title: 'update: update syscalls tables.'
          body: |
            This autogenerated PR updates the tables of syscalls from kernel ${{ env.VERSION }}. Do not edit this PR.
            ```
          commit-message: 'update: update syscalls tables.'
          token: ${{ secrets.GITHUB_TOKEN }}
