name: Update Syscalls Tables

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 2' # Each tuesday

jobs:
  update-tables:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # without x32 headers we get i386 data for x32
      - name: install x32 headers
        run: sudo apt-get install libc6-dev-x32

      - name: Checkout syscalls-table ⤵️
        uses: actions/checkout@v4
        with:
          ref: master
      
      - name: Checkout linux ⤵️
        run: |
          git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git linux/ --depth=1
          
      - name: Fetch linux version
        working-directory: linux/
        run: |
          LINUX_VER=$(make kernelversion)
          echo "VERSION=$LINUX_VER" >> $GITHUB_ENV
          
      - name: Bump syscalls-tables
        run: |
          make KERNELSRC=$GITHUB_WORKSPACE/linux/
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          signoff: true
          base: master
          branch: update/tables
          title: 'update: update syscalls tables.'
          body: |
            This autogenerated PR updates the tables of syscalls from kernel ${{ env.VERSION }}. Do not edit this PR.
            ```
          commit-message: 'update: update syscalls tables.'
          token: ${{ secrets.GITHUB_TOKEN }}
